"""
main.py — FastAPI application entry point.

Startup sequence:
  1. FastAPI app is created
  2. RecEngine is instantiated (fits all 5 models — takes ~1 second)
  3. Static files are mounted at /static → serves the frontend
  4. API routes are mounted at /api

Usage:
  uvicorn api.main:app --reload --port 8000
  Then open: http://localhost:8000/static/index.html

The interactive API docs (auto-generated by FastAPI) are at:
  http://localhost:8000/docs
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from api.routes import router
from engine.recommender import RecEngine


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Fit all recommendation models on startup."""
    app.state.engine = RecEngine()
    yield
    # Nothing to clean up on shutdown (all state is in-memory)


app = FastAPI(
    title="Spotify Rec Engine",
    description="A learning project demonstrating 5 recommendation algorithms",
    version="1.0.0",
    lifespan=lifespan,
)

# Allow browser JS to call the API (required if serving from a different origin)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)

# Serve the frontend HTML/CSS/JS from /static
app.mount("/static", StaticFiles(directory="static"), name="static")

# All recommendation API endpoints under /api
app.include_router(router, prefix="/api")
